lib/discuss_web/router.ex
defmodule DiscussWeb.Router do
  use DiscussWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DiscussWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/topics/new", TopicController, :new
    post "/topics", TopicController, :create
    get "/topics", TopicController, :index
    get "/topics/:id/edit", TopicController, :edit
    put "/topics/:id", TopicController, :update
    delete "/topics/:id", TopicController, :delete
  end

  scope "/auth", DiscussWeb do
    pipe_through :browser

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", DiscussWeb do
  #   pipe_through :api
  # end
end

lib/discuss/account/account.ex
defmodule Discuss.Account do
  @moduledoc """
  The Account context.
  """

  import Ecto.Query, warn: false
  alias Discuss.Repo
  alias Discuss.Account.User

  def create_user(attrs \\ %{}) do
    %User{}
    |> User.changeset(attrs)
    |> Repo.insert
  end

end

lib/discuss/account/user.ex
defmodule Discuss.Account.User do
  use Ecto.Schema
  import Ecto.Changeset


  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string

    timestamps()
  end

  @doc false
  def changeset(user, attrs) do
    user
    |> cast(attrs, [:email, :provider, :token])
    |> validate_required([:email, :provider, :token])
  end
end

lib/discuss/application.ex
defmodule Discuss.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Discuss.Repo, []),
      # Start the endpoint when the application starts
      supervisor(DiscussWeb.Endpoint, []),
      # Start your own worker by calling: Discuss.Worker.start_link(arg1, arg2, arg3)
      # worker(Discuss.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Discuss.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    DiscussWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/discuss/forum/forum.ex
defmodule Discuss.Forum do
  @moduledoc """
  The Forum context.
  """

  import Ecto.Query, warn: false
  alias Discuss.Repo
  alias Discuss.Forum.Topic

  def create_topic(attrs \\ %{}) do
    %Topic{}
    |> Topic.changeset(attrs)
    |> Repo.insert()
  end

  def change_topic(%Topic{} = topic) do
    Topic.changeset(topic, %{})
  end

  def all_topics do
    Repo.all(Topic)
  end

  def get_topic(id) do
    case Repo.get(Topic, id) do
      nil -> {:error, "Could not find topic"}
      topic -> {:ok, topic}
    end
  end

  def update_topic(%Topic{} = topic, attrs) do
    topic
    |> Topic.changeset(attrs)
    |> Repo.update
  end

  def delete_topic(%Topic{} = topic) do
    case Repo.delete(topic) do
      {:ok, topic} -> :ok
      {:error, _} -> :error
    end
  end
end

lib/discuss/forum/topic.ex
defmodule Discuss.Forum.Topic do
  use Ecto.Schema
  import Ecto.Changeset


  schema "topics" do
    field :title, :string

    timestamps()
  end

  @doc false
  def changeset(topic, attrs) do
    topic
    |> cast(attrs, [:title])
    |> validate_required([:title])
  end
end

lib/discuss/repo.ex
defmodule Discuss.Repo do
  use Ecto.Repo, otp_app: :discuss

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/discuss_web/controllers/auth_controller.ex
defmodule DiscussWeb.AuthController do
  use DiscussWeb, :controller
  plug Ueberauth

  def callback(conn, params) do

  end
end

lib/discuss_web/controllers/fallback_controller.ex
defmodule DiscussWeb.FallbackController do
  use DiscussWeb, :controller

  def call(conn, {:error, msg}) when is_binary(msg) do
    conn
    |> put_flash(:error, msg)
    |> redirect(to: topic_path(conn, :index))
  end

  def call(conn, {:error, %Ecto.Changeset{}}) do
    action_name = action_name(conn)
    conn
    |> put_flash(:error, get_msg(action_name))
    |> redirect(to: topic_path(conn, :index))
  end

  defp get_msg(action_name) do
    Map.get(error_msgs(), action_name, "There was an error")
  end

  defp error_msgs do
    %{create: "There was an error creating your topic.",
      update: "There was an error updating your topic",
      delete: "There was an error deleting your topic"}
  end

  defp error_routes do
    %{create: :new,
      update: :edit,
      delete: :index}
  end
end

lib/discuss_web/controllers/page_controller.ex
defmodule DiscussWeb.PageController do
  use DiscussWeb, :controller

  def index(conn, _params) do
    redirect(conn, to: topic_path(conn, :index))
  end
end

lib/discuss_web/controllers/topic_controller.ex
defmodule DiscussWeb.TopicController do
  use DiscussWeb, :controller

  alias Discuss.Forum
  alias Discuss.Forum.Topic

  action_fallback DiscussWeb.FallbackController

  def new(conn, _params) do
    changeset = Forum.change_topic(%Topic{})

    render conn, "new.html", changeset: changeset
  end

  def create(conn, %{"topic" => topic_params}) do
    with {:ok, topic} <- Forum.create_topic(topic_params) do
      conn
      |> put_flash(:info, "Topic created")
      |> redirect(to: topic_path(conn, :index))
    end
  end

  def index(conn, _params) do
    topics = Forum.all_topics
    render conn, "index.html", topics: topics
  end

  def edit(conn, %{"id" => topic_id}) do
    with {:ok, topic} <- Forum.get_topic(topic_id) do
      changeset = Forum.change_topic(topic)
      render(conn, "edit.html", topic: topic, changeset: changeset)
    end
  end

  def update(conn, %{"id" => id, "topic" => topic_params}) do
    with {:ok, topic} <- Forum.get_topic(id),
         {:ok, topic} <- Forum.update_topic(topic, topic_params) do

      conn
      |> put_flash(:info, "Topic updated successfully")
      |> redirect(to: topic_path(conn, :index))
    end
  end

  def delete(conn, %{"id" => id}) do
    with {:ok, topic} <- Forum.get_topic(id),
         :ok <- Forum.delete_topic(topic) do

           conn
           |> put_flash(:info, "Topic deleted")
           |> redirect(to: topic_path(conn, :index))
         end
  end
end

lib/discuss_web/views/error_view.ex
defmodule DiscussWeb.ErrorView do
  use DiscussWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/discuss_web/views/layout_view.ex
defmodule DiscussWeb.LayoutView do
  use DiscussWeb, :view
end

lib/discuss_web/views/page_view.ex
defmodule DiscussWeb.PageView do
  use DiscussWeb, :view
end

lib/discuss_web/views/shared_view.ex
defmodule DiscussWeb.SharedView do
  use DiscussWeb, :view
end

lib/discuss_web/views/topic_view.ex
defmodule DiscussWeb.TopicView do
  use DiscussWeb, :view
end

lib/discuss_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discuss!</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
  </head>

  <body>
    <nav class="teal lighten-2">
      <div class="nav-wrapper">
        <div class="container">
          <a href="/" class="brand-logo">Discuss</a>
        </div>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <%= link to: auth_path(@conn, :request, "github") do %>
              Login <i class="material-icons right">lock</i>
          <% end %>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container">
      <%= render DiscussWeb.SharedView, "_banner.html", assigns %>
      <div  class="row"></div>
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>

lib/discuss_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/discuss_web/templates/shared/_banner.html.eex
<%= if info_msg = get_flash(@conn, :info) do %>
  <div class="row" id="alert_box">
    <div class="col s12 m12">
      <div class="card blue lighten-3">
        <div class="row">
          <div class="col s12 m10">
            <div class="card-content white-text">
              <p><%= info_msg %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= if error_msg = get_flash(@conn, :error) do %>
  <div class="row" id="alert_box">
    <div class="col s12 m12">
      <div class="card red darken-1">
        <div class="row">
          <div class="col s12 m10">
            <div class="card-content white-text">
              <p><%= error_msg %></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

lib/discuss_web/templates/topic/edit.html.eex
<div class="row">
  <div class="col offset-s3 s6">
    <%= form_for @changeset, topic_path(@conn, :update, @topic), fn f -> %>
      <div class="form-group">
        <div class="input-field">
          <%= text_input f, :title, class: "validate" %>
          <%= label f, :title %>
          <%= error_tag f, :title %>
        </div>

        <div class="right-align">
          <%= submit class: "btn teal lighten-2 waves-effect waves-light" do %>
            <i class="material-icons right">send</i>Save Topic
          <% end%>
        </div>
      </div>
    <% end %>
  </div>
</div>

lib/discuss_web/templates/topic/index.html.eex
<ul class="collection with-header">
  <li class="collection-header"><h4>Topics</h4></li>
  <%= for topic <- @topics do %>
      <li class="collection-item">
        <%= topic.title %>
        <div class="right">
          <%= link "Edit", to: topic_path(@conn, :edit, topic) %> |
          <%= link "Delete", to: topic_path(@conn, :delete, topic), method: :delete %>
        </div>
      </li>
  <% end %>
</ul>

<div class="fixed-action-btn">
  <%= link to: topic_path(@conn, :new), class: "btn-floating btn-large waves-effect waves-light red" do %>
    <i class="material-icons">add</i>
  <% end %>
</div>

lib/discuss_web/templates/topic/new.html.eex
<div class="row">
  <div class="col offset-s3 s6">
    <%= form_for @changeset, topic_path(@conn, :create), fn f -> %>
      <div class="form-group">
        <div class="input-field">
          <%= text_input f, :title, class: "validate" %>
          <%= label f, :title %>
          <%= error_tag f, :title %>
        </div>

        <div class="right-align">
          <%= submit class: "btn teal lighten-2 waves-effect waves-light" do %>
            <i class="material-icons right">send</i>Save Topic
          <% end%>
        </div>
      </div>
    <% end %>
  </div>
</div>